#!/data/data/com.termux/files/usr/bin/bash

# Atualiza e instala o básico
pkg update -y && pkg upgrade -y
pkg install python git wget openssl python-psutil -y

# Instala as bibliotecas Python (Tudo em uma linha só para não dar erro)
pip install requests pytz pyjwt pycryptodome rich colorama flask discord python-socketio --no-cache-dir

# Cria pasta, baixa e instala os 4 clones
mkdir -p ~/downloads_apks && cd ~/downloads_apks
for i in {1..4}; do
    wget -q https://github.com/frogxtrem-sys/clones/releases/download/v1/clone$i.apk
    su -c "pm install -r $PWD/clone$i.apk"
done

# Entra no seu projeto principal
cd ~
git clone https://github.com/frogxtrem-sys/principal
cd principal
python main.py
